stan-dev/rstantools

vignettes/developer-guidelines.Rmd

It took me a bit of digging to figure out that you need the `args = "--preclean"` flag for install_github to work. I've added a note in the vignette to alert people to that (and recommend that they include such a note in their own README files). I'm not particularly wedded to this wording/location in the vignette but think it's important to clarify this.

add note on how to install from github source

---

DESCRIPTION
R/rstan_package_skeleton.R
tests/testthat/test-rstan_package_skeleton.R
vignettes/developer-guidelines.Rmd

This is already necessary to call `rstan_package.skeleton` because rstanarm merged the 2.17 branch into master and so some files that it tries to download no longer exist on the master branch or are otherwise wrong. And CRAN is not going to accept new uploads for a couple of weeks starting tomorrow.

update to correspond to rstanarm 2.17.2

---

R/rstan_package_skeleton.R

A comma appears to be required in the @ useDynLib declaration. Adding this into the guidance provided in Read-and-delete-me

add comma to useDynLib roxygen declaration

---

DESCRIPTION
R/rstan_package_skeleton.R
man/rstan_package_skeleton.Rd
tests/testthat/test-rstan_package_skeleton.R
vignettes/minimal-rstan-package.Rmd

Closes #25 
@bgoodri This PR gets rid of calling `utils::package.skeleton` inside of `rstan_package_skeleton` and replaces it with Hadley's much friendlier `usethis::create_package`. It also updates @sieste's step-by-step vignette to create the rstanlm package in a temporary directory.

Switch to usethis::create_package 

---

R/rstan_package_skeleton.R
vignettes/minimal-rstan-package.Rmd

devtools::install() previously had a "local" argument that could be used to re-build a package without compiling Stan code. The arguments have changed (as of devtools version 2.0.0?), and "quick" is now the relevant argument.

change devtools::install argument from local to quick

---

R/rstan_create_package.R

This fixes #67 for me.
```
> dir.create("tmp")
> rstan_create_package("tmp")
Error: Directory 'tmp' already exists.
```

Better error message if the directory already exists

---

R/rstan_create_package.R

First attempt at fixing #65, it works well when creating a new package with `rstan_create_package`. I'm not sure how to deal with `use_rstan`, perhaps it's best not to do anything in that case?

Add generated C++ files to .gitignore and .Rbuildignore

---

R/rstan_package_utils.R
R/use_rstan.R

Fixes #82. 
Checks if first line is #! interpreter line and if so puts the "don't edit by hand" message on the second line instead of the first. This avoids the new r cmd check note reported in #82.

fix r cmd check note about #! interpreter line

---

R/rstan_config.R
inst/include/sys/Makevars
inst/include/sys/Makevars.win

This PR updates `rstan_config()` to define `USE_STANC3` prior to including stan headers, and also adds functionality for building packages with stan models of just standalone functions

Fix RStan 2.26 building & Standalone functions

---

.github/workflows/check-standard.yaml
DESCRIPTION
R/rstan_config.R
vignettes/minimal-rstan-package.Rmd

Duplicate of #88, but with the base branch coming from `stan-dev/rstantools` rather than my fork, to allow the Github Actions to run

Fix additions and add GHA R CMD CHECK

---

R/rstan_config.R

This PR adds the functionality needed for handling the `.stanfunctions` file type introduced in Stan 2.29 - which is essentially just a Stan file consisting solely of function definitions, but without the enclosing `functions` block.
As the included `stanc3` is not directly compatible, this PR simply wraps the functions in a `functions` block, and treats the file like any other standalone-functions file to be exported

Add compatibility with .stanfunctions files

---

R/rstan_config.R

#94 overrides the default `isystem` when calling `rstan::stanc()`, which breaks some packages. This PR appends extra inlcudes to the default `isystem`. Some of them may not be required.

`rstan_config`: Fix includes

---

.github/workflows/check-standard.yaml
DESCRIPTION
inst/include/sys/Makevars
inst/include/sys/Makevars.win

As discussed over [on the forums](https://discourse.mc-stan.org/t/cran-note-for-package-using-stan-suggest-c-17/30247), CRAN has begun issuing a `NOTE` when the requested C++ standard is lower than C++17. This PR updates the rstantools-provided Makevars to request the higher standard.
I've run reverse-dependency checks and all packages continue to build and pass. This will break the current `rstan` 2.26, but I've already opened a PR with the needed patches [here](https://github.com/stan-dev/math/pull/2873)

Update C++ Standard to C++17

---

.github/workflows/check-standalone.yaml
.github/workflows/check-standard.yaml
R/rstan_config.R

This PR updates the handling of exporting standalone stan functions in packages for compatibility with the 2.26 versions of StanHeaders and rstan
I've added a github actions workflow which tests against a branch of the `lgpr` package which uses this feature to ensure that it works with all combinations of rstan and StanHeaders

Fix compatibility for exporting standalone functions, add tests

---

DESCRIPTION
NEWS.md
R/init_cpp.R
R/nsamples.R
man/init_cpp.Rd
man/nsamples.Rd

deprecate `nsamples` (should use `ndraws` from posterior instead) and `init_cpp` (not used anymore)

deprecations

---

.github/workflows/check-standalone.yaml
R/rstan_config.R

There's a small bug in the exporting of standalone functions under rstan 2.31, where the extraction of plain return types was failing if two functions started with the same string (e.g., `fun1` and `fun1_2`) but had different return types.
This PR updates the regex and updates the workflow to additionally test against the `experimental` rstan branch

Bugfix for standalone functions under 2.31

---

R/rstan_config.R

Packages exporting standalone functions via `rstantools` have been receiving the following warning during submission ([here](https://github.com/plloydsmith/rmdcev/pull/8#issuecomment-1481981897) and [here](https://github.com/jtimonen/lgpr/pull/26#issuecomment-1468784322)):
```
* checking whether package 'rmdcev' can be installed ... WARNING
Found the following significant warnings:
WARNING: The tools required to build C++ code for R were not found
```
This warning is a false positive, as the packages compile without issue.
I've identified that this is coming from calling `rstan::expose_stan_functions()` with `rstan 2.21` when not using RStudio (it has also been seen [on the forums before](https://discourse.mc-stan.org/t/testing-user-defined-functions-with-newer-stan-functions/25040))
This …

Suppress false-positive warning for standalone functions

---

DESCRIPTION
R/rstan_config.R
inst/include/sys/Makevars
inst/include/sys/Makevars.win

CRAN notified me that they uploaded a new version of rstantools with the only difference being that when checking the version numbers of rstan and StanHeaders we now use strings instead of numerics (e.g. '2.26' instead of 2.26).
This PR updates the GitHub repo to match what CRAN did.

update to match CRAN's patched version

---

.github/workflows/check-standalone.yaml
.github/workflows/check-standard.yaml
R/rstan_config.R

This PR resolves a similar issue as this `cmdstanr` PR: https://github.com/stan-dev/cmdstanr/pull/847
After 2.33 `stanc3` will emit plain types for standalone functions instead of `auto`, so we no longer need to pre-process the `hpp` to do this ourselves.
This PR is needed for rstan 2.33 compatibility with packages like `lgpr` and `rmdcev` which export standalone functions during installation

Fix packages with stanfunctions under rstan 2.33+

---

R/loo-functions.R

I'd like to add `loo_epred()` to `brms` https://github.com/paul-buerkner/brms/issues/1641, and this would be helpful in `rstantools`

add loo_epred

---

R/rstan_config.R

This is a minimal fix for #129. I cannot reproduce the project with my packages (also the version of RBest on github doesn't cause the problem reported): @wds15 could you verify that it solves your problem?

Retrieve the package name from the DESCRIPTION file

---

NEWS.md
R/rstan_config.R

When the DESCRIPTION file is not present, the package name is inferred to be `basename(pkgdir)`, which is what it used to be before #130.
Fixes #135.

Add fallback package name in case the DESCRIPTION file cannot be read

---

DESCRIPTION
R/rstantools-package.R

This fixes the following warning when compiling the documentation:
> rstantools-package.R:24: `@docType "package"` is deprecated.

Fix roxygen2 warning
